# This is a basic workflow to help you get started with Actions

name: Test Reusable Workflow

# Controls when the workflow will run
on:
  workflow_call: 
    inputs:
      optional-value:
        description: 'Test Optional Value'
        default: 'optional default value'
        required: false
        type: string
      required-value: 
        description: 'Test Required Value'
        default: 'required default value'
        required: true
        type: string
      script:
        description: Script containing stuff
        required: false
        default: ''
        type: string
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Print Values
        run: |
          echo "Optional: ${{ inputs.optional-value }}"
          echo "Required: ${{ inputs.required-value }}"
      - name: Run Script
        run: | 
          dir=$(pwd)
          echo "Dir: $dir"
          sh ./scripts/echo_script.sh
